version: "2.0"

nlu:
- intent: web3.md
  examples: |
    - what is web3?
    - web3
    - web3 vs web2
    - what on earth is web 3
    - tell me about web3
    - web3 crypto
    - why web3

- intent: crypto_wallets.md
  examples: |
    - what is a crypto wallets
    - good crypto wallets
    - crypto wallet
    - wallet
    - free wallet
    - best wallet
    - wallet download
    - safe wallets
    - easy to use wallets